- type: job
  id: Triarius
  name: job-name-triarius
  description: job-description-triarius
  playTimeTracker: JobTriarius
  weight: 20
  startingGear: TriariusGear
  icon: "JobIconSecurityOfficer"
  joinNotifyCrew: true
  supervisors: job-supervisors-security
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  - Cryogenics

- type: startingGear
  id: TriariusGear
  equipment:
    outerClothing: ClothingOuterArmorBasic
    id: SecurityCadetPDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolMk58
  storage:
    back:
    - Flash
    - MagazinePistol
